import Link from "next/link";
import "./globals.css";
import { Control } from "@/Control";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {

  // 7. {cache: 'no-store'}를 사용함으로써 기존의 캐시를 담지않고 바로 랜더링 즉 화면에 보여줄 수 있게 만듬
  const res = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics', {cache: 'no-store'});
  const topics = await res.json();

  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((item) => (
              <li key={item.id}><Link href={`/read/${item.id}`}>{item.title}</Link></li>
            ))}
        </ol>
        {children}
        <Control />
          
      </body>
    </html>
  );
}
